### ISSUE TITLE
InferResolversStrict not checking resolver params correctly

### ISSUE THREAD

**Issue by mlafeldt** [stepci/garph#58] opened 2023-04-24 08:59 UTC
Hey, here's something I'd like to understand:

Given the following code, `InferResolversStrict` will happily accept `getUsername` as a resolver, although its arguments are wrong. I think this is related to the fact that the first arg is supposed to be `parent: any`, which checks against `id: string`. However, the number of args isn't enforced either (it should be 4 instead of 1).

(I don't think it's a problem with Deno's TS compiler options as those are pretty [strict by default](https://deno.com/manual@v1.32.5/advanced/typescript/configuration).)

Please enlighten me. 😄 

```ts
import { graphql } from "npm:graphql"
import { buildSchema, g, InferResolversStrict } from "npm:garph"

function getUsername(id: string): string {
  return "User#" + id
}

const queryType = g.type("Query", {
  username: g.string().args({
    id: g.id(),
  }),
})

const resolvers: InferResolversStrict<
  { Query: typeof queryType },
  {}
> = {
  Query: {
    username: getUsername, // wrong
    // username: (_, args, __, ___) => getUsername(args.id), // correct
  },
}

const query = Deno.args[0]
const schema = buildSchema({ g, resolvers })
const result = await graphql({
  schema,
  source: query,
  rootValue: resolvers,
})

console.log(JSON.stringify(result, null, 2))
```

**Comment by mishushakov** [comment] 2023-04-24 09:32
Good finding, Mathias! Will investigate soon

**Comment by mishushakov** [comment] 2023-06-12 18:00
The number of arguments can be 0-4 and the return type has to be correct, otherwise you will be getting an error.

I couldn't reproduce. Do you still experience the error. Have you tried starting a new project w/o Deno?

<img width="697" alt="Screenshot 2023-06-12 at 19 56 21" src="https://github.com/stepci/garph/assets/10400064/07992766-a04c-48e0-bf0c-20dd365de229">

<img width="1018" alt="Screenshot 2023-06-12 at 19 56 27" src="https://github.com/stepci/garph/assets/10400064/35f17589-9d54-4953-9007-f9ef691b8265">

**Comment by mishushakov** [comment] 2023-06-12 18:02
You could also just manually cast the types

<img width="699" alt="Screenshot 2023-06-12 at 20 01 54" src="https://github.com/stepci/garph/assets/10400064/1cfcfbd3-0db9-4095-ac6b-53e8855d9006">

**Comment by mishushakov** [comment] 2023-06-12 18:02
Will be closing as it's not reproducible

**Closed by mishushakov** 2023-06-12 18:02 UTC
